name: LyricsFlip Contracts

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scarb fmt --check
        working-directory: onchain
      - run: scarb build
        working-directory: onchain
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: snforge test
        working-directory: onchain